// export const rooms=[];
// rooms[1] ='Direktor'          ;
// rooms[2] ='Administracija'    ;
// rooms[3] ='Vodja prodaje'     ;'Prodaja'
// rooms[4] ='Prodaja'           ;'Kakovost' 
// rooms[5] ='Ho.Re.Ca'          ;'Laboratorij'  
// rooms[6] ='Kakovost'          ;'Server soba'  
// rooms[7] ='Laboratorij'       ;'Avla zgoraj' 
// rooms[8] ='Server soba'       ;'Sejna soba'   
// rooms[9] ='Sejna soba'        ;'Ho.Re.Ca'
// rooms[10]='Avla zgoraj'       ;'Vodja prodaje'
// rooms[11]='Sprejemna pisarna' ;'Avla spodaj' 
// rooms[12]='Finance'           ;'Vodja servisa'
// rooms[13]='Vodja servisa'     ;'Finance'  
// rooms[14]='Avla spodaj'       ;'Sprejemna pisarna'


// export const rooms=[];
// rooms[1] ='Direktor'          ;
// rooms[2] ='Administracija'    ;
// rooms[10]='Vodja prodaje'     ;
// rooms[3] ='Prodaja'           ;
// rooms[9] ='Ho.Re.Ca'          ;
// rooms[4] ='Kakovost'          ;
// rooms[5] ='Laboratorij'       ;
// rooms[6] ='Server soba'       ;
// rooms[8] ='Sejna soba'        ;
// rooms[7] ='Avla zgoraj'       ;
// rooms[14]='Sprejemna pisarna' ;
// rooms[13]='Finance'           ;
// rooms[12]='Vodja servisa'     ;
// rooms[11]='Avla spodaj'       ;


export const rooms=[];
rooms[1] ='Direktor'          ;
rooms[2] ='Administracija'    ;
rooms[4] ='Vodja prodaje'     ;
rooms[6] ='Prodaja'           ;
rooms[7] ='Ho.Re.Ca'          ;
rooms[8] ='Kakovost'          ;
rooms[10]='Laboratorij'       ;
rooms[9] ='Server soba'       ;
rooms[5] ='Sejna soba'        ;
rooms[3] ='Avla zgoraj'       ;
rooms[14]='Sprejemna pisarna' ;
rooms[13]='Finance'           ;
rooms[12]='Vodja servisa'     ;
rooms[11]='Avla spodaj'       ;